# -*- coding: utf-8 -*-
"""best-books.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NFcjAf4W_qoxtgOLj1KD7YhxYsQPwzrK
"""

#Importing libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import RandomForestRegressor

#Loading Dataset
df = pd.read_csv("books.csv")
df.head()

df.columns

subset = df.head(200)
print(subset)

subset.isnull().sum()

subset.columns

#Plotting Top 5 Books
fig = plt.figure(figsize=(12,6))
ax = fig.add_subplot(1,1,1)
ax.bar(subset["authors"][:5],subset["average_rating"][:5])
plt.show()

# Histogram of publication years
plt.hist(df['original_publication_year'].dropna(), bins=30)
plt.xlabel('Publication Year')
plt.ylabel('Count')
plt.title('Distribution of Publication Years')
plt.show()

# Histogram of average ratings
plt.hist(df['average_rating'], bins=30)
plt.xlabel('Average Rating')
plt.ylabel('Count')
plt.title('Distribution of Average Ratings')
plt.show()

# Histogram of average ratings
plt.hist(df['average_rating'], bins=30)
plt.xlabel('Average Rating')
plt.ylabel('Count')
plt.title('Distribution of Average Ratings')
plt.show()

# Bar chart of authors
plt.figure(figsize=(10, 6))
df['authors'].value_counts().head(10).plot(kind='bar')
plt.xlabel('Author')
plt.ylabel('Count')
plt.title('Top 10 Authors by Number of Books')
plt.show()

# Bar chart of languages
plt.figure(figsize=(10, 6))
df['language_code'].value_counts().plot(kind='bar')
plt.xlabel('Language')
plt.ylabel('Count')
plt.title('Distribution of Books by Language')
plt.show()

# Scatter plot of average rating vs. ratings count
plt.scatter(df['ratings_count'], df['average_rating'], alpha=0.5)
plt.xlabel('Ratings Count')
plt.ylabel('Average Rating')
plt.title('Average Rating vs. Ratings Count')
plt.show()

# Pie chart of languages
plt.figure(figsize=(8, 8))
df['language_code'].value_counts().plot(kind='pie', autopct='%1.1f%%')
plt.title('Distribution of Books by Language')
plt.ylabel('')
plt.show()

# Box plot of average ratings
import seaborn as sns
sns.boxplot(df['average_rating'])
plt.title('Box Plot of Average Ratings')
plt.show()

# Violin plot of language vs. average rating
plt.figure(figsize=(10, 6))
sns.violinplot(x='language_code', y='average_rating', data=df)
plt.xlabel('Language')
plt.ylabel('Average Rating')
plt.title('Distribution of Average Ratings by Language')
plt.xticks(rotation=45)
plt.show()